package formulario;

import dao.FuncionarioDao;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mapeamento.Funcionario;

public class FormFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarFuncionrio
     */
    public FormFuncionario() {
        initComponents();
        btAtualizar.setVisible(false);
        preencherTabela();
        this.setIconImage(new ImageIcon("Icone-CriativaModas.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbFuncionario = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        btCadastrarForn = new javax.swing.JButton();
        btImprimir1 = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btIExcluir = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        edPesquisa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btSalvarPdf1 = new javax.swing.JButton();
        btCancelarcONSULTA = new javax.swing.JButton();
        tbCadastro = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        edNomeCompleto = new javax.swing.JTextField();
        edEndereco = new javax.swing.JTextField();
        edCEP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edIdade = new javax.swing.JTextField();
        btAvancarPP = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        edBairro = new javax.swing.JTextField();
        edNumeroResidencial = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        edTelefone = new javax.swing.JFormattedTextField();
        edCpf = new javax.swing.JFormattedTextField();
        edRG = new javax.swing.JFormattedTextField();
        edCarteiraDeTrabalho = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        cbCargoDeOcupacaoNaEmpresa = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbEstadoCivil = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btVoltarSP = new javax.swing.JButton();
        btAvancarSP = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        edCidade = new javax.swing.JTextField();
        edNacionalidade = new javax.swing.JTextField();
        edRua = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        edDataDeNascimento = new javax.swing.JFormattedTextField();
        edTituloDeEletor = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cbTipoSangineo = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        edNomeDoPai = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        edNomeDaMae = new javax.swing.JTextField();
        btAvancarTP = new javax.swing.JButton();
        btVoltarTP = new javax.swing.JButton();
        edTempoServico = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        edJornadaDeTrabalho = new javax.swing.JTextField();
        edDataDeAdmissao = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        edSalarioAtual = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cbFormaDePagamento = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        cbCategoriaDeHabilitacao = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        btCadastrar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btVoltarQP = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        edAgenciaBancaria = new javax.swing.JTextField();
        edCarteiraNascionalDeHabilitacao = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FUNCIONARIO");

        jLabel29.setText("Pesquisar:");

        btCadastrarForn.setText("CADASTRAR NOVO FORNECEDOR");
        btCadastrarForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarFornActionPerformed(evt);
            }
        });

        btImprimir1.setText("IMPRIMIR");

        btEditar.setText("EDITAR");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btIExcluir.setText("EXCLUIR");
        btIExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIExcluirActionPerformed(evt);
            }
        });

        jLabel30.setText("LISTA DOS FUNCIONARIOS CADASTRADOS");

        edPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edPesquisaActionPerformed(evt);
            }
        });
        edPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edPesquisaKeyPressed(evt);
            }
        });

        tabela.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID DO FUNCIONARIO", "NOME FORNECEDOR", "CPF", "TELEFONE", "CARGO FUNCIONARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela);

        btSalvarPdf1.setText("SALVAR EM PDF");

        btCancelarcONSULTA.setText("SAIR DA CONSULTA");
        btCancelarcONSULTA.setAlignmentY(5.0F);
        btCancelarcONSULTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarcONSULTAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btSalvarPdf1)
                .addGap(18, 18, 18)
                .addComponent(btImprimir1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btEditar)
                .addGap(18, 18, 18)
                .addComponent(btIExcluir)
                .addGap(92, 92, 92))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel30))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel29)
                        .addGap(3, 3, 3)
                        .addComponent(edPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btCadastrarForn)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btCancelarcONSULTA))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(edPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrarForn))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarPdf1)
                    .addComponent(btImprimir1)
                    .addComponent(btEditar)
                    .addComponent(btIExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelarcONSULTA)
                .addContainerGap())
        );

        tbFuncionario.addTab("Lista", jPanel6);

        jLabel1.setText("CEP");

        jLabel2.setText("REFERENCIA ENDEREÇO");

        jLabel3.setText("CARTEIRA DE INDENTIDADE (RG)");

        jLabel4.setText("NOME COMPLETO");

        jLabel5.setText("CPF");

        jLabel6.setText("TELEFONE");

        jLabel7.setText("CARTEIRA DE TRABALHO");

        jLabel8.setText("IDADE");

        btAvancarPP.setText("AVANÇAR");
        btAvancarPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarPPActionPerformed(evt);
            }
        });

        jLabel31.setText("BAIRRO");

        jLabel32.setText("NUMERO RESIDENCIAL");

        try {
            edTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+55(###) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            edCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            edRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edRG.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            edCarteiraDeTrabalho.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.######.##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edCarteiraDeTrabalho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(edNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(edCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(edCarteiraDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(edRG, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edNumeroResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(250, 250, 250))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(edBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31)
                                .addComponent(edTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edCpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAvancarPP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(edCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edNumeroResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edCarteiraDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btAvancarPP)
                .addGap(25, 25, 25))
        );

        tbCadastro.addTab("Primeiro Passo", jPanel2);

        cbCargoDeOcupacaoNaEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GERENTE", "VENDEDOR", "CAIXA" }));

        jLabel9.setText("CARGO DE OCUPAÇÃO NA EMPRESA");

        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLTEIRO(A)", "CASADO(A)", "VIUVA(O)", "SEPARADO(A)", "DIVORCIADO(A)", "UNIÃO ESTÁVEL" }));
        cbEstadoCivil.setSelectedIndex(-1);

        jLabel10.setText("ESTADO CIVIL");

        jLabel11.setText("DATA DE NASCIMENTO");

        jLabel12.setText("NASCIONALIDADE");

        jLabel13.setText("ESTADO");

        jLabel14.setText("CIDADE");

        jLabel15.setText("TITULO DE ELITOR");

        btVoltarSP.setText("VOLTAR");
        btVoltarSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarSPActionPerformed(evt);
            }
        });

        btAvancarSP.setText("AVANÇAR");
        btAvancarSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarSPActionPerformed(evt);
            }
        });

        jLabel16.setText("INSIRA UM IMAGEM");

        jLabel33.setText("RUA");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-adicionar-câmera.png"))); // NOI18N

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACRE", "ALAGOAS", "AMAPÁ", "AMAZONAS", "BAHIA", "CEARÁ", "ESPÍRITO SANTO", "GOIÁS", "MARANHÃO", "MATO GROSSO", "MATO GROSSO DO SUL", "MINAS GERAIS", "PARÁ", "PARAÍBA", "PARANÁ", "PERNAMBUCO", "PIAUÍ", "RIO DE JANEIRO", "RIO GRANDE DO NORTE", "RIO GRANDE DO SUL", "RONDÔNIA", "RORAIMA", "SANTA CATARINA", "SÃO PAULO", "SERGIPE", "TOCANTINS", "DISTRITO FEDERAL" }));
        cbEstado.setSelectedIndex(-1);
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });

        try {
            edDataDeNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edDataDeNascimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            edTituloDeEletor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbCargoDeOcupacaoNaEmpresa, 0, 300, Short.MAX_VALUE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(edNacionalidade, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(edDataDeNascimento))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edTituloDeEletor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel15))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(262, 262, 262)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btVoltarSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAvancarSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(90, 90, 90)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(edRua, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edTituloDeEletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(8, 8, 8)
                        .addComponent(cbCargoDeOcupacaoNaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltarSP)
                    .addComponent(btAvancarSP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbCadastro.addTab("Segundo Passo", jPanel3);

        jLabel17.setText("DATA DE ADMISSÃO");

        jLabel20.setText("JORNADA DE TRABALHO");

        jLabel21.setText("TIPO SANGUÍNEO");

        cbTipoSangineo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-" }));
        cbTipoSangineo.setSelectedIndex(-1);

        jLabel22.setText("NOME DO PAI");

        jLabel23.setText("NOME DA MÃE");

        edNomeDaMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNomeDaMaeActionPerformed(evt);
            }
        });

        btAvancarTP.setText("AVANÇAR");
        btAvancarTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarTPActionPerformed(evt);
            }
        });

        btVoltarTP.setText("VOLTAR");
        btVoltarTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarTPActionPerformed(evt);
            }
        });

        jLabel34.setText("TEMPO SERVIÇO");

        try {
            edDataDeAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edDataDeAdmissao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edNomeDaMae)
                    .addComponent(edNomeDoPai)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 620, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btVoltarTP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAvancarTP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(edJornadaDeTrabalho)
                                .addGap(190, 190, 190))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22)
                                    .addComponent(edDataDeAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(cbTipoSangineo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(edTempoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edTempoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edDataDeAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoSangineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edJornadaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edNomeDoPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edNomeDaMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAvancarTP)
                    .addComponent(btVoltarTP))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        tbCadastro.addTab("Terceiro Passo", jPanel4);

        jLabel24.setText("SALÁRIO ATUAL");

        jLabel25.setText("CARTEIRA NASCIONAL DE HABILAÇÃO (CNH)");

        jLabel26.setText("FORMA DE PAGAMENTO");

        cbFormaDePagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A VISTA", "A PRASO" }));
        cbFormaDePagamento.setSelectedIndex(-1);

        jLabel27.setText("CATEGORIA DE HABILITAÇÃO");

        cbCategoriaDeHabilitacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "AB", " " }));
        cbCategoriaDeHabilitacao.setSelectedIndex(-1);

        jLabel28.setText("REFEIÇÃO:");

        jRadioButton1.setText("POSSUI");

        jRadioButton2.setText("NÃO POSSUI");

        jRadioButton3.setText("NÃO POSSUI CNH");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });

        btCadastrar.setText("CADASTRAR");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btCancelar.setText("CANCELAR");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btVoltarQP.setText("VOLTAR");
        btVoltarQP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarQPActionPerformed(evt);
            }
        });

        btAtualizar.setText("ATUALIZAR");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        jLabel18.setText("AGÊNCIA BANCÁRIA");

        try {
            edCarteiraNascionalDeHabilitacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edSalarioAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addComponent(edCarteiraNascionalDeHabilitacao)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel27)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel26)
                                        .addComponent(cbFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbCategoriaDeHabilitacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel28)))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btVoltarQP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edAgenciaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edAgenciaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edSalarioAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategoriaDeHabilitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edCarteiraNascionalDeHabilitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCancelar)
                            .addComponent(btVoltarQP))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAtualizar)
                        .addGap(24, 24, 24))))
        );

        tbCadastro.addTab("Quarto Passo", jPanel5);

        tbFuncionario.addTab("Cadastro", tbCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbFuncionario)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbFuncionario)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edNomeDaMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNomeDaMaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNomeDaMaeActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        Funcionario f = new Funcionario();
        f.setAgenciaBancaria(edAgenciaBancaria.getText());
        f.setBairro(edBairro.getText());
        f.setCargoDoFuncionario(cbCargoDeOcupacaoNaEmpresa.getSelectedItem().toString());
        f.setCategoriaCnh(cbCategoriaDeHabilitacao.getSelectedItem().toString());
        f.setCep(edCEP.getText());
        f.setCidade(edCidade.getText());
        f.setCnh(edCarteiraNascionalDeHabilitacao.getText());
        f.setComplementoEndereco(edEndereco.getText());
        f.setCpf(edCpf.getText());
        f.setDataDeAdmissao(edDataDeAdmissao.getText());
        f.setDataNasc(edDataDeNascimento.getText());
        f.setEstado(cbEstado.getSelectedItem().toString());
        f.setEstadoCivil(cbEstadoCivil.getSelectedItem().toString());
        f.setFormaDePagamento(cbFormaDePagamento.getSelectedItem().toString());
        f.setIdade(Integer.parseInt(edIdade.getText()));
        f.setJornadaDeTrabalho(edJornadaDeTrabalho.getText());
        f.setNaturalidade(edNacionalidade.getText());
        f.setNomeCompleto(edNomeCompleto.getText());
        f.setNomeDaMae(edNomeDaMae.getText());
        f.setNomeDoPai(edNomeDoPai.getText());
        f.setNumeroResidencial(edNumeroResidencial.getText());
        f.setRg(edRG.getText());
        f.setRua(edRua.getText());
        f.setSalarioAtual(Float.parseFloat(edSalarioAtual.getText()));
        f.setTelefone(edTelefone.getText());
        f.setTempoServico(edTempoServico.getText());
        f.setTipoSanguineo(cbTipoSangineo.getSelectedItem().toString());
        f.setTituloDeEleitor(edTituloDeEletor.getText());
        FuncionarioDao fdao = new FuncionarioDao();
        fdao.inserir(f);
        preencherTabela();
        btCadastrar.setVisible(true);
        btAtualizar.setVisible(false);
        tbFuncionario.setSelectedIndex(0);
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btVoltarQPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarQPActionPerformed
        tbCadastro.setSelectedIndex(2);
    }//GEN-LAST:event_btVoltarQPActionPerformed

    private void btCadastrarFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarFornActionPerformed
        btAtualizar.setVisible(false);
        btCadastrar.setVisible(true);
        tbFuncionario.setSelectedIndex(1);
    }//GEN-LAST:event_btCadastrarFornActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        Funcionario f = new Funcionario();
        int indice = tabela.getSelectedRow();
        preencherTabela(f);
        if (indice >= 0) {
            try {
                f.setIdFuncionario(Integer.parseInt(tabela.getValueAt(indice, 0).toString()));
                edNomeCompleto.setText(tabela.getValueAt(indice, 1).toString());
                edCpf.setText(tabela.getValueAt(indice, 2).toString());
                edTelefone.setText(tabela.getValueAt(indice, 3).toString());
                edAgenciaBancaria.setText(f.getAgenciaBancaria());
                edBairro.setText(f.getBairro());
                edCEP.setText(f.getCep());
                edCpf.setText(f.getCpf());
                edCarteiraDeTrabalho.setText(f.getCarteiraDeTrabalho());
                edCarteiraNascionalDeHabilitacao.setText(f.getCnh());
                edCidade.setText(f.getCidade());
                edDataDeAdmissao.setText(f.getDataDeAdmissao());
                edDataDeNascimento.setText(f.getDataNasc());
                edEndereco.setText(f.getComplementoEndereco());
                edIdade.setText(String.valueOf(f.getIdade()));
                edNacionalidade.setText(f.getNaturalidade());
                edNomeDaMae.setText(f.getNomeDaMae());
                edNomeDoPai.setText(f.getNomeDoPai());
                edNumeroResidencial.setText(f.getNumeroResidencial());
                edRG.setText(f.getRg());
                edRua.setText(f.getRua());
                edSalarioAtual.setText(String.valueOf(f.getSalarioAtual()));
                edTelefone.setText(f.getTelefone());
                edTempoServico.setText(f.getTempoServico());
                edTituloDeEletor.setText(f.getTituloDeEleitor());
                cbCargoDeOcupacaoNaEmpresa.setSelectedItem(f.getCargoDoFuncionario());
                cbCategoriaDeHabilitacao.setSelectedItem(f.getCategoriaCnh());
                cbEstado.setSelectedItem(f.getEstado());
                cbEstadoCivil.setSelectedItem(f.getEstadoCivil());
                cbFormaDePagamento.setSelectedItem(f.getFormaDePagamento());
                edJornadaDeTrabalho.setText(f.getJornadaDeTrabalho());
                cbTipoSangineo.setSelectedItem(f.getTipoSanguineo());
                btAtualizar.setVisible(true);
                btCadastrar.setVisible(false);
                tbFuncionario.setSelectedIndex(1);
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro Ao Carregar Dados");
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btIExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIExcluirActionPerformed
        int indice = tabela.getSelectedRow();
        Funcionario f = new Funcionario();
        FuncionarioDao fdao = new FuncionarioDao();
        if (indice >= 0) {
            f.setIdFuncionario(Integer.parseInt(tabela.getValueAt(indice, 0).toString()));
            f.setNomeCompleto(tabela.getValueAt(indice, 1).toString());
            fdao.deletar(f);
            preencherTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        }
    }//GEN-LAST:event_btIExcluirActionPerformed

    private void edPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edPesquisaActionPerformed

    private void edPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edPesquisaKeyPressed
        preencherTabela(edPesquisa.getText());
    }//GEN-LAST:event_edPesquisaKeyPressed

    private void btCancelarcONSULTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarcONSULTAActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarcONSULTAActionPerformed

    private void btAvancarPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarPPActionPerformed
        tbCadastro.setSelectedIndex(1);
    }//GEN-LAST:event_btAvancarPPActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        Funcionario f = new Funcionario();
        f.setAgenciaBancaria(edAgenciaBancaria.getText());
        f.setBairro(edBairro.getText());
        f.setCargoDoFuncionario(cbCargoDeOcupacaoNaEmpresa.getSelectedItem().toString());
        f.setCategoriaCnh(cbCategoriaDeHabilitacao.getSelectedItem().toString());
        f.setCep(edCEP.getText());
        f.setCidade(edCidade.getText());
        f.setCnh(edCarteiraNascionalDeHabilitacao.getText());
        f.setComplementoEndereco(edEndereco.getText());
        f.setCpf(edCpf.getText());
        f.setDataDeAdmissao(edDataDeAdmissao.getText());
        f.setDataNasc(edDataDeNascimento.getText());
        f.setEstado(cbEstado.getSelectedItem().toString());
        f.setEstadoCivil(cbEstadoCivil.getSelectedItem().toString());
        f.setFormaDePagamento(cbFormaDePagamento.getSelectedItem().toString());
        f.setIdade(Integer.parseInt(edIdade.getText()));
        f.setJornadaDeTrabalho(edJornadaDeTrabalho.getText());
        f.setNaturalidade(edNacionalidade.getText());
        f.setNomeCompleto(edNomeCompleto.getText());
        f.setNomeDaMae(edNomeDaMae.getText());
        f.setNomeDoPai(edNomeDoPai.getText());
        f.setNumeroResidencial(edNumeroResidencial.getText());
        f.setRg(edRG.getText());
        f.setRua(edRua.getText());
        f.setSalarioAtual(Float.parseFloat(edSalarioAtual.getText()));
        f.setTelefone(edTelefone.getText());
        f.setTempoServico(edTempoServico.getText());
        f.setTipoSanguineo(cbTipoSangineo.getSelectedItem().toString());
        f.setTituloDeEleitor(edTituloDeEletor.getText());
        FuncionarioDao fdao = new FuncionarioDao();
        fdao.atualizar(f);
        
        btCadastrar.setVisible(true);
        btAtualizar.setVisible(false);
        preencherTabela();
        tbCadastro.setSelectedIndex(0);
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        edAgenciaBancaria.setText(null);
        edBairro.setText(null);
        edCEP.setText(null);
        edCpf.setText(null);
        edCarteiraDeTrabalho.setText(null);
        edCarteiraNascionalDeHabilitacao.setText(null);
        edCidade.setText(null);
        edDataDeAdmissao.setText(null);
        edDataDeNascimento.setText(null);
        edEndereco.setText(null);
        edIdade.setText(null);
        edNacionalidade.setText(null);
        edNomeCompleto.setText(null);
        edNomeDaMae.setText(null);
        edNomeDoPai.setText(null);
        edNumeroResidencial.setText(null);
        edPesquisa.setText(null);
        edRG.setText(null);
        edRua.setText(null);
        edSalarioAtual.setText(null);
        edTelefone.setText(null);
        edTempoServico.setText(null);
        edTituloDeEletor.setText(null);
        cbCargoDeOcupacaoNaEmpresa.setSelectedIndex(-1);
        cbCategoriaDeHabilitacao.setSelectedIndex(-1);
        cbEstado.setSelectedIndex(-1);
        cbEstadoCivil.setSelectedIndex(-1);
        cbFormaDePagamento.setSelectedIndex(-1);
        edJornadaDeTrabalho.setText(null);
        cbTipoSangineo.setSelectedIndex(-1);
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btAvancarTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarTPActionPerformed
        tbCadastro.setSelectedIndex(3);
    }//GEN-LAST:event_btAvancarTPActionPerformed

    private void btVoltarTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarTPActionPerformed
        tbCadastro.setSelectedIndex(1);
    }//GEN-LAST:event_btVoltarTPActionPerformed

    private void btAvancarSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarSPActionPerformed
        tbCadastro.setSelectedIndex(2);
    }//GEN-LAST:event_btAvancarSPActionPerformed

    private void btVoltarSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarSPActionPerformed
        tbCadastro.setSelectedIndex(0);
    }//GEN-LAST:event_btVoltarSPActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
        edCarteiraNascionalDeHabilitacao.setVisible(false);
        edCarteiraNascionalDeHabilitacao.setText(null);
    }//GEN-LAST:event_jRadioButton3MouseClicked

    public void preencherTabela() {
        FuncionarioDao fdao = new FuncionarioDao();
        List<Funcionario> lista = fdao.listarTodos();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setRowCount(0);
        for (Funcionario f : lista) {
            modelo.addRow(new Object[]{f.getIdFuncionario(), f.getNomeCompleto(), f.getCpf(), f.getTelefone(), f.getCargoDoFuncionario()});
        }
    }

    public void preencherTabela(String nome) {
        FuncionarioDao fdao = new FuncionarioDao();
        List<Funcionario> lista = fdao.listarTodos(nome);
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setRowCount(0);
        for (Funcionario f : lista) {
            modelo.addRow(new Object[]{f.getIdFuncionario(), f.getNomeCompleto(), f.getCpf(), f.getTelefone(), f.getCargoDoFuncionario()});
        }
    }

    public void preencherTabela(Funcionario fun) {
        FuncionarioDao fdao = new FuncionarioDao();
        List<Funcionario> lista = fdao.listarTodos();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setRowCount(0);
        for (Funcionario f : lista) {
            modelo.addRow(new Object[]{f.getIdFuncionario(), f.getNomeCompleto(), f.getCpf(), f.getTelefone(), f.getCargoDoFuncionario()});
            fun = f;
        }
    }

    public void iniciarCadastro() {
        tbFuncionario.setSelectedIndex(1);
    }

    public void iniciarConsulta() {
        tbFuncionario.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btAvancarPP;
    private javax.swing.JButton btAvancarSP;
    private javax.swing.JButton btAvancarTP;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCadastrarForn;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelarcONSULTA;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btIExcluir;
    private javax.swing.JButton btImprimir1;
    private javax.swing.JButton btSalvarPdf1;
    private javax.swing.JButton btVoltarQP;
    private javax.swing.JButton btVoltarSP;
    private javax.swing.JButton btVoltarTP;
    private javax.swing.JComboBox<String> cbCargoDeOcupacaoNaEmpresa;
    private javax.swing.JComboBox<String> cbCategoriaDeHabilitacao;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbEstadoCivil;
    private javax.swing.JComboBox<String> cbFormaDePagamento;
    private javax.swing.JComboBox<String> cbTipoSangineo;
    private javax.swing.JTextField edAgenciaBancaria;
    private javax.swing.JTextField edBairro;
    private javax.swing.JTextField edCEP;
    private javax.swing.JFormattedTextField edCarteiraDeTrabalho;
    private javax.swing.JFormattedTextField edCarteiraNascionalDeHabilitacao;
    private javax.swing.JTextField edCidade;
    private javax.swing.JFormattedTextField edCpf;
    private javax.swing.JFormattedTextField edDataDeAdmissao;
    private javax.swing.JFormattedTextField edDataDeNascimento;
    private javax.swing.JTextField edEndereco;
    private javax.swing.JTextField edIdade;
    private javax.swing.JTextField edJornadaDeTrabalho;
    private javax.swing.JTextField edNacionalidade;
    private javax.swing.JTextField edNomeCompleto;
    private javax.swing.JTextField edNomeDaMae;
    private javax.swing.JTextField edNomeDoPai;
    private javax.swing.JTextField edNumeroResidencial;
    private javax.swing.JTextField edPesquisa;
    private javax.swing.JFormattedTextField edRG;
    private javax.swing.JTextField edRua;
    private javax.swing.JTextField edSalarioAtual;
    private javax.swing.JFormattedTextField edTelefone;
    private javax.swing.JTextField edTempoServico;
    private javax.swing.JFormattedTextField edTituloDeEletor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela;
    private javax.swing.JTabbedPane tbCadastro;
    private javax.swing.JTabbedPane tbFuncionario;
    // End of variables declaration//GEN-END:variables
}
