package formulario;

import dao.ClienteDao;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mapeamento.Cliente;

public class FormCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormClientee
     */
    public FormCliente() {
        initComponents();
        btAtualizar.setVisible(false);
        preencherTabela();
        this.setIconImage(new ImageIcon("Icone-CriativaModas.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbClietne = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        btCadastrarCli = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btIExcluir = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        edPesquisa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btSalvarPdf = new javax.swing.JButton();
        btCancelarcONSULTA = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tbCadastro = new javax.swing.JTabbedPane();
        Passo1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edNomeCompleto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edRg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edTelefone = new javax.swing.JFormattedTextField();
        edCpf = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edBairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        edCep = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        edRua = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        edNdeResidencia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        edComplemento = new javax.swing.JTextField();
        btCancelar = new javax.swing.JButton();
        btAvançar = new javax.swing.JButton();
        edCidade = new javax.swing.JTextField();
        edIdade = new javax.swing.JTextField();
        Passo4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        edPessoaReferencia = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        edTelefonePessoaRef = new javax.swing.JFormattedTextField();
        lbReferencia = new javax.swing.JLabel();
        edLojaReferencia = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        edCarteiraTrabalho = new javax.swing.JTextField();
        brReferencia = new javax.swing.JRadioButton();
        btVoltar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel24.setText("Pesquisar:");

        btCadastrarCli.setText("CADASTRAR NOVO CLIENTE");
        btCadastrarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarCliActionPerformed(evt);
            }
        });

        btImprimir.setText("IMPRIMIR");

        btEditar.setText("EDITAR");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btIExcluir.setText("EXCLUIR");
        btIExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIExcluirActionPerformed(evt);
            }
        });

        jLabel25.setText("LISTA DOS CLIENTE CADASTRADOS");

        edPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edPesquisaActionPerformed(evt);
            }
        });
        edPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edPesquisaKeyPressed(evt);
            }
        });

        tabela.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID DO CLIENTE", "NOME DO CLIENTE", "CPF DO CLIENTE", "TELEFONE", "RG", "PESSOA REFERENCIA", "NUMERO DA PESSOA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela);

        btSalvarPdf.setText("SALVAR EM PDF");

        btCancelarcONSULTA.setText("SAIR DA CONSULTA");
        btCancelarcONSULTA.setAlignmentY(5.0F);
        btCancelarcONSULTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarcONSULTAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btSalvarPdf)
                .addGap(18, 18, 18)
                .addComponent(btImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btEditar)
                .addGap(18, 18, 18)
                .addComponent(btIExcluir)
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel24)
                        .addGap(3, 3, 3)
                        .addComponent(edPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btCadastrarCli)))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btCancelarcONSULTA))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(edPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrarCli))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarPdf)
                    .addComponent(btImprimir)
                    .addComponent(btEditar)
                    .addComponent(btIExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelarcONSULTA)
                .addContainerGap())
        );

        tbClietne.addTab("Lista", jPanel1);

        Passo1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setText("NOME COMPLETO DO CLIENTE");

        jLabel2.setText("TELEFONE");

        jLabel3.setText("CPF DO CLIENTE");

        jLabel4.setText("RG DO CLIENTE");

        edRg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("IDADE");

        try {
            edTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+55(###) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            edCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("ESTADO");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACRE", "ALAGOAS", "AMAPÁ", "AMAZONAS", "BAHIA", "CEARÁ", "ESPÍRITO SANTO", "GOIÁS", "MARANHÃO", "MATO GROSSO", "MATO GROSSO DO SUL", "MINAS GERAIS", "PARÁ", "PARAÍBA", "PARANÁ", "PERNAMBUCO", "PIAUÍ", "RIO DE JANEIRO", "RIO GRANDE DO NORTE", "RIO GRANDE DO SUL", "RONDÔNIA", "RORAIMA", "SANTA CATARINA", "SÃO PAULO", "SERGIPE", "TOCANTINS", "DISTRITO FEDERAL" }));
        cbEstado.setSelectedIndex(-1);
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });

        jLabel7.setText("CIDADE");

        jLabel8.setText("BAIRRO");

        edBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edBairroActionPerformed(evt);
            }
        });

        jLabel9.setText("CEP");

        try {
            edCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-### ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edCep.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setText("RUA");

        edRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edRuaActionPerformed(evt);
            }
        });

        jLabel11.setText("NÚMERO DA RESIDÊNCIA");

        edNdeResidencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setText("COMPLEMENTO");

        btCancelar.setText("CANCELAR");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btAvançar.setText("AVANÇAR");
        btAvançar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvançarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Passo1Layout = new javax.swing.GroupLayout(Passo1);
        Passo1.setLayout(Passo1Layout);
        Passo1Layout.setHorizontalGroup(
            Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Passo1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAvançar)
                .addGap(76, 76, 76))
            .addGroup(Passo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(edNdeResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Passo1Layout.createSequentialGroup()
                        .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edCep, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(edBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edRua, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Passo1Layout.createSequentialGroup()
                        .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(Passo1Layout.createSequentialGroup()
                                    .addGap(259, 259, 259)
                                    .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(edRg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)))
                                .addComponent(edNomeCompleto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(edCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(edIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        Passo1Layout.setVerticalGroup(
            Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Passo1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Passo1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Passo1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edRua, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Passo1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(edCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Passo1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edNdeResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(Passo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAvançar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tbCadastro.addTab("Passo 1", Passo1);

        Passo4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel20.setText("NOME PESSOA DE REFERÊNCIA");

        jLabel21.setText("TELEFONE");

        try {
            edTelefonePessoaRef.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+55(###) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edTelefonePessoaRef.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbReferencia.setText("1ª LOJA DE REFERÊNCIA");

        jLabel22.setText("CARTEIRA DE TRABALHO");

        brReferencia.setText("NÃO POSSUI REFERÊNCIA");
        brReferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brReferenciaMouseClicked(evt);
            }
        });
        brReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brReferenciaActionPerformed(evt);
            }
        });
        brReferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brReferenciaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                brReferenciaKeyReleased(evt);
            }
        });

        btVoltar.setText("VOLTAR");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btCadastrar.setText("FINALIZAR  CADASTRO");
        btCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAtualizar.setText("ATUALIZAR CADASTRO");
        btAtualizar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Passo4Layout = new javax.swing.GroupLayout(Passo4);
        Passo4.setLayout(Passo4Layout);
        Passo4Layout.setHorizontalGroup(
            Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Passo4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Passo4Layout.createSequentialGroup()
                        .addComponent(brReferencia)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Passo4Layout.createSequentialGroup()
                        .addGroup(Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Passo4Layout.createSequentialGroup()
                                .addComponent(btVoltar)
                                .addGap(122, 122, 122)
                                .addComponent(btCadastrar))
                            .addGroup(Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(edLojaReferencia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Passo4Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(197, 197, 197))
                                    .addComponent(edPessoaReferencia, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(lbReferencia)))
                        .addGroup(Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Passo4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addGroup(Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel21)
                                    .addComponent(edTelefonePessoaRef, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(jLabel22)
                                    .addComponent(edCarteiraTrabalho))
                                .addGap(59, 59, 59))
                            .addGroup(Passo4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btAtualizar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        Passo4Layout.setVerticalGroup(
            Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Passo4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edPessoaReferencia)
                    .addComponent(edTelefonePessoaRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbReferencia)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edLojaReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edCarteiraTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Passo4Layout.createSequentialGroup()
                        .addComponent(brReferencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVoltar))
                    .addGroup(Passo4Layout.createSequentialGroup()
                        .addGap(0, 123, Short.MAX_VALUE)
                        .addGroup(Passo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );

        tbCadastro.addTab("Passo 2", Passo4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbCadastro)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbCadastro)
        );

        tbClietne.addTab("Cadastro", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbClietne)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbClietne, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarCliActionPerformed
        btCancelarActionPerformed(evt);
        btCadastrar.setVisible(true);
        btAtualizar.setVisible(false);
        tbClietne.setSelectedIndex(1);
        tbCadastro.setSelectedIndex(0);
    }//GEN-LAST:event_btCadastrarCliActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        Cliente c = new Cliente();
        int indice = tabela.getSelectedRow();

        if (indice >= 0) {
            try {
                c.setIdCliente(Integer.parseInt(tabela.getValueAt(indice, 0).toString()));
                edNomeCompleto.setText(tabela.getValueAt(indice, 1).toString());
                edTelefone.setText(tabela.getValueAt(indice, 2).toString());
                edCpf.setText(tabela.getValueAt(indice, 3).toString());
                edRg.setText(tabela.getValueAt(indice, 4).toString());
                edIdade.setText(tabela.getValueAt(indice, 5).toString());
                cbEstado.setSelectedItem(tabela.getValueAt(indice, 6).toString());
                edCidade.setText(tabela.getValueAt(indice, 7).toString());
                edBairro.setText(tabela.getValueAt(indice, 8).toString());
                edCep.setText(tabela.getValueAt(indice, 9).toString());
                edRua.setText(tabela.getValueAt(indice, 10).toString());
                edNdeResidencia.setText(tabela.getValueAt(indice, 11).toString());
                edComplemento.setText(tabela.getValueAt(indice, 12).toString());
                edPessoaReferencia.setText(tabela.getValueAt(indice, 13).toString());
                edTelefonePessoaRef.setText(tabela.getValueAt(indice, 14).toString());
                edLojaReferencia.setText(tabela.getValueAt(indice, 15).toString());
                edCarteiraTrabalho.setText(tabela.getValueAt(indice, 16).toString());
                btAtualizar.setVisible(true);
                btCadastrar.setVisible(false);
                tbClietne.setSelectedIndex(1);
                tbCadastro.setSelectedIndex(0);
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro Ao Carregar Dados");
        }


    }//GEN-LAST:event_btEditarActionPerformed

    private void btIExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIExcluirActionPerformed
        int indice = tabela.getSelectedRow();
        Cliente c = new Cliente();
        ClienteDao pDao = new ClienteDao();
        if (indice >= 0) {
            c.setIdCliente(Integer.parseInt(tabela.getValueAt(indice, 0).toString()));
            c.setNomeCompleto(tabela.getValueAt(indice, 1).toString());
            pDao.deletar(c);
            preencherTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        }
    }//GEN-LAST:event_btIExcluirActionPerformed

    private void edPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edPesquisaActionPerformed

    private void edPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edPesquisaKeyPressed
        preencherTabela(edPesquisa.getText());
    }//GEN-LAST:event_edPesquisaKeyPressed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void edBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edBairroActionPerformed

    private void edRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edRuaActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        edNomeCompleto.setText(null);
        edTelefone.setText(null);
        edCpf.setText(null);
        edRg.setText(null);
        edIdade.setText(null);
        cbEstado.setSelectedIndex(-1);
        edCidade.setText(null);
        edBairro.setText(null);
        edCep.setText(null);
        edRua.setText(null);
        edNdeResidencia.setText(null);
        edComplemento.setText(null);
        edPessoaReferencia.setText(null);
        edTelefonePessoaRef.setText(null);
        edLojaReferencia.setText(null);
        edCarteiraTrabalho.setText(null);
        btAtualizar.setVisible(false);
        btCadastrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed
    private void btAvançarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvançarActionPerformed
        tbCadastro.setSelectedIndex(1);
    }//GEN-LAST:event_btAvançarActionPerformed

    private void brReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brReferenciaActionPerformed

    }//GEN-LAST:event_brReferenciaActionPerformed

    private void brReferenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brReferenciaKeyPressed

    }//GEN-LAST:event_brReferenciaKeyPressed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        tbCadastro.setSelectedIndex(0);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        Cliente c = new Cliente();
        c.setNomeCompleto(edNomeCompleto.getText());
        c.setTelefone(edTelefone.getText());
        c.setCpf(edCpf.getText());
        c.setRg(edRg.getText());
        c.setIdade(Integer.parseInt(edIdade.getText()));
        c.setEstado(cbEstado.getSelectedItem().toString());
        c.setCidade(edCidade.getText());
        c.setBairro(edBairro.getText());
        c.setCep(edCep.getText());
        c.setRua(edRua.getText());
        c.setNumeroResidencial(edNdeResidencia.getText());
        c.setComplementoEndereco(edComplemento.getText());
        c.setPessoaReferencia(edPessoaReferencia.getText());
        c.setNumeroPessoaReferencia(edTelefonePessoaRef.getText());
        c.setLojaDeReferencia(edLojaReferencia.getText());
        c.setCarteiraDeTrabalho(edCarteiraTrabalho.getText());

        ClienteDao cDao = new ClienteDao();
        cDao.inserir(c);
        preencherTabela();

        edNomeCompleto.setText(null);
        edTelefone.setText(null);
        edCpf.setText(null);
        edRg.setText(null);
        edIdade.setText(null);
        cbEstado.setSelectedIndex(-1);
        edCidade.setText(null);
        edBairro.setText(null);
        edCep.setText(null);
        edRua.setText(null);
        edNdeResidencia.setText(null);
        edComplemento.setText(null);
        edPessoaReferencia.setText(null);
        edTelefonePessoaRef.setText(null);
        edLojaReferencia.setText(null);
        edCarteiraTrabalho.setText(null);
        btAtualizar.setVisible(false);
        btCadastrar.setVisible(true);
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        Cliente c = new Cliente();
        c.setNomeCompleto(edNomeCompleto.getText());
        c.setTelefone(edTelefone.getText());
        c.setCpf(edCpf.getText());
        c.setRg(edRg.getText());
        c.setIdade(Integer.parseInt(edIdade.getText()));
        c.setEstado(cbEstado.getSelectedItem().toString());
        c.setCidade(edCidade.getText());
        c.setBairro(edBairro.getText());
        c.setCep(edCep.getText());
        c.setRua(edRua.getText());
        c.setNumeroResidencial(edNdeResidencia.getText());
        c.setComplementoEndereco(edComplemento.getText());
        c.setPessoaReferencia(edPessoaReferencia.getText());
        c.setNumeroPessoaReferencia(edTelefonePessoaRef.getText());
        c.setLojaDeReferencia(edLojaReferencia.getText());
        c.setCarteiraDeTrabalho(edCarteiraTrabalho.getText());

        ClienteDao cDao = new ClienteDao();
        cDao.atualizar(c);
        preencherTabela();

       edNomeCompleto.setText(null);
        edTelefone.setText(null);
        edCpf.setText(null);
        edRg.setText(null);
        edIdade.setText(null);
        cbEstado.setSelectedIndex(-1);
        edCidade.setText(null);
        edBairro.setText(null);
        edCep.setText(null);
        edRua.setText(null);
        edNdeResidencia.setText(null);
        edComplemento.setText(null);
        edPessoaReferencia.setText(null);
        edTelefonePessoaRef.setText(null);
        edLojaReferencia.setText(null);
        edCarteiraTrabalho.setText(null);
        btAtualizar.setVisible(false);
        btCadastrar.setVisible(true);
        tbClietne.setSelectedIndex(0);
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void brReferenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brReferenciaKeyReleased
        
    }//GEN-LAST:event_brReferenciaKeyReleased

    private void brReferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brReferenciaMouseClicked

    }//GEN-LAST:event_brReferenciaMouseClicked

    private void btCancelarcONSULTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarcONSULTAActionPerformed
        FormMenu form = new FormMenu();
        form.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btCancelarcONSULTAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    public void preencherTabela() {
        ClienteDao cDao = new ClienteDao();
        List<Cliente> lista = cDao.listarTodos();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setRowCount(0);
        for (Cliente c : lista) {
            modelo.addRow(new Object[]{c.getIdCliente(), c.getNomeCompleto(), c.getCpf(), c.getTelefone(), c.getRg(),
                c.getPessoaReferencia(), c.getNumeroPessoaReferencia()});
        }
    }

    public void preencherTabela(String nome) {
        ClienteDao cDao = new ClienteDao();
        List<Cliente> lista = cDao.listarTodos(nome);
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setRowCount(0);
        for (Cliente c : lista) {
            modelo.addRow(new Object[]{c.getIdCliente(), c.getNomeCompleto(), c.getCpf(), c.getTelefone(), c.getRg(),
                c.getPessoaReferencia(), c.getNumeroPessoaReferencia()});
        }
    }
    
    public void iniciarCadastro(){
         tbClietne.setSelectedIndex(1);
    }
    public void iniciarConsulta(){
         tbClietne.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Passo1;
    private javax.swing.JPanel Passo4;
    private javax.swing.JRadioButton brReferencia;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btAvançar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCadastrarCli;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelarcONSULTA;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btIExcluir;
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btSalvarPdf;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JTextField edBairro;
    private javax.swing.JTextField edCarteiraTrabalho;
    private javax.swing.JFormattedTextField edCep;
    private javax.swing.JTextField edCidade;
    private javax.swing.JTextField edComplemento;
    private javax.swing.JFormattedTextField edCpf;
    private javax.swing.JTextField edIdade;
    private javax.swing.JTextField edLojaReferencia;
    private javax.swing.JTextField edNdeResidencia;
    private javax.swing.JTextField edNomeCompleto;
    private javax.swing.JTextField edPesquisa;
    private javax.swing.JTextField edPessoaReferencia;
    private javax.swing.JTextField edRg;
    private javax.swing.JTextField edRua;
    private javax.swing.JFormattedTextField edTelefone;
    private javax.swing.JFormattedTextField edTelefonePessoaRef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbReferencia;
    private javax.swing.JTable tabela;
    private javax.swing.JTabbedPane tbCadastro;
    private javax.swing.JTabbedPane tbClietne;
    // End of variables declaration//GEN-END:variables
}
